### ISSUE TITLE
Exception: HTML Parse Error: Missing argument 1 for...

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-fulltextsearch#194]
PHP7.0 / SS4 / fulltextsearch 3.0.0-beta1

When running Solr_Reindex and adding  `Page`, there seems to be a mismatch in the no. params requored in a method somewhere in the fulltextsearch module. The reindex completes, so it's OK for now for my purposes. If I get time, I'll dig deeper.

Partial stacktrace:

```
[2017-12-21 08:50:05] silverstripe\fulltextsearch\solr\tasks\solr_reindex.INFO: Adding Page [] []
ERROR [UNKNOWN TYPE, ERRNO ]: Exception: HTML Parse Error: Missing argument 1 for SilverStripe\ORM\DataExtension::canEdit() in /home/user/htdocs/somesite/vendor/silverstripe/fulltextsearch/src/Search/Indexes/SearchIndex.php:505
Stack trace:
#0 /home/user/htdocs/somesite/vendor/silverstripe/framework/src/ORM/DataExtension.php(91): SilverStripe\FullTextSearch\Search\Indexes\SearchIndex->SilverStripe\FullTextSearch\Search\Indexes\{closure}(2, 'Missing argumen...', '/home/user...', 91, Array)
#1 [internal function]: SilverStripe\ORM\DataExtension->canEdit()
#2 /home/user/htdocs/somesite/vendor/silverstripe/framework/src/Core/Extensible.php(144): call_user_func_array(Array, Array)

```

**Comment by robbieaverill** [comment]
Thanks. This _could_ be another module, since the `flush_dirty_indexes` method registers a shutdown handler which sometimes trips out at the end of the middleware chain.

Could you provide a bigger stack trace?

This is likely caused by a DataExtension subclass defining canEdit without making the `$member` parameter default to null.

There aren't any of these, or any calls to canEdit in this module

**Comment by robbieaverill** [comment]
Feel free to reopen, but I don't think this is caused by this module
