### ISSUE TITLE
Can't detect application dir - skipping default index creation

### ISSUE THREAD

**Issue by robbyahn** [silverstripe/silverstripe-fulltextsearch#248]
Hi guys,

I am wondering that the instruction us still valid for the quick start script - fulltextsearch_quickstart. 
have run the script then shows that "Can't detect application dir - skipping default index creation".

I am using ss4 and install cwp/cwp-search.

Thanks.

**Comment by robbieaverill** [comment]
What is your project directory called? It looks like the script auto-detects `app` and `mysite`, are you using something else?

**Comment by NightJar** [comment]
The project directory is configurable @robbieaverill - in the least I'd hope the code leverages this to correctly identify the "application dir" (assuming this is what that error means).

**Comment by robbieaverill** [comment]
Unfortunately the script in question does not, which is why I asked

**Comment by robbieaverill** [comment]
@robbyahn please feel free to reopen if you have a specific bug report, otherwise there are great [community support options](http://www.silverstripe.org/community/#introduction) where you can get help including [our forum](https://forum.silverstripe.org), [Stack Overflow (remember to tag as silverstripe)](http://stackoverflow.com/questions/tagged/silverstripe) and even [Slack](http://silverstripe.org/slack).

Sorry we can't be of more help and good luck resolving your problem!

**Comment by taoceanz** [comment]
This is closed now, but @robbyahn ensure you're calling the script from your project root i.e. same directory your composer.json should be in.
The directory you should be in should look similar to this:
```
$> ls
app composer.json error.log public README.md themes vendor
```
Once in that directory, run `$> vendor/bin/fulltextsearch_quickstart`.
What ever directory you run vendor/bin/fulltextsearch_quickstart in is the directory it will search for either app or mysite.
